name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  watch:
    types: [started]

jobs:
  build:
    runs-on: self-hosted
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget python3-docutils

    - name: Clone source code
      env:
        KERNEL: 3.4
      run: |
        if [ "$KERNEL" = "4.4" ] ; then
          git clone --depth=1 https://github.com/MeIsReallyBa/padavan-4.4.git ~/rt-n56u
        else
          git clone --depth=1 https://github.com/chongshengB/rt-n56u.git ~/rt-n56u
        fi
        cd ~/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p ~/images/

    - name: Build Firmware
      env:
        TNAME: K2P
        KERNEL: 3.4
      run: |
        cd ~/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
          echo "configs/templates/$TNAME.config not found "
          exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config

        if [ "$KERNEL" = "4.4" ] ; then
          echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=v" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config
        else
          echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config
        fi

        ./clear_tree
        ./build_firmware_modify "$TNAME" 0
        mv -f images/*.trx ~/images/

    - name: Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: ~/images/
